language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
sudo: false
addons:
  apt:
    packages:
    - wget
before_install:
    - sh -e /etc/init.d/xvfb start
script:
    - wget https://download.qt.io/archive/qt/5.5/5.5.1/qt-opensource-linux-x64-android-5.5.1.run
    - chmod u+x qt-opensource-linux-x64-android-5.5.1.run
    - ./qt-opensource-linux-x64-android-5.5.1.run --dump-binary-data -o QT
    - ls QT

